Temporal implementation of the array to export from rof to lnd
ESCOMP/mizuRoute pull request #274
Opened 2022-04-04 18:43 UTC by nmizukami

xxxxx

Fix #273

2022-04-28 21:44 UTC, nmizukami commented on route/build/cpl/RtmMod.F90
> +    ! put reach flux variables to associated HRUs
removing duplicated code lines is good practice.

2022-05-04 20:21 UTC, ekluzek requested changes
IF possible I'd like to see you reduce the code duplication. That's my only feedback.

2022-05-05 01:56 UTC, nmizukami commented
commit 948b96ce12a0db26c710be363a953db60ce22930 removed duplicated lines.

2022-05-05 01:59 UTC, nmizukami commented
Hi @ekluzek,  wondering if there is any good way to check if rtmCTL%discharge(:) is correct order.

2022-05-05 12:06 UTC, merged