exporting volume (volr) to land model and handling negative qgwl
ESCOMP/mizuRoute pull request #297
Opened 2022-08-06 20:15 UTC by nmizukami

- turn on volume export
- handling negative qgwl.  Three options: putting 1) all, 2) negative, or 3) > threshold qgwl to `rtmCTL%direct` array 

resolve #164

2022-08-17 16:57 UTC, ekluzek requested changes
The new control variables need to be added to the settings control file or the namelist. It also looks like they aren't fully enabled yet. I assume you will fully enable them in this PR?

2022-08-17 16:57 UTC, ekluzek commented on route/build/cpl/RtmVar.F90
> +  character(len=32), public            :: bypass_routing_option = 'direct_in_place' ! bypass routing model method
Looks like currently it's hardcoded to only allow direct_in_place

2022-08-23 16:56 UTC, nmizukami commented on route/build/cpl/RtmMod.F90
> +              rtmCTL%volr(ix) = vol_hru/rtmCTL%area(ix)
without this if statement, volr get NaN at headwater HRUs (I believe) where volume is zero. Will investigate this later.

2022-08-23 17:04 UTC, nmizukami commented on route/build/cpl/RtmVar.F90
> +  character(len=32), public            :: qgwl_runoff_option ='threshold'           ! method for handling qgwl runoff
qgwl_runoff_option is moved to saved variables in mizuRoute side

2022-08-23 17:06 UTC, nmizukami commented on route/build/cpl/RtmVar.F90
> +  character(len=32), public            :: bypass_routing_option = 'direct_in_place' ! bypass routing model method
`bypass_routing_option` is moved to saved variables in mizuRoute shared code and both `qgwl_runoff_option` and `bypass_routing_option` are provided in control file

2022-08-24 17:25 UTC, ekluzek commented
@nmizukami and I looked at this together and this is ready to bring in.

2022-08-24 17:38 UTC, merged