IRF water take
ESCOMP/mizuRoute pull request #430
Opened 2023-09-17 16:59 UTC by nmizukami

Make water abstraction and injection consistent with the other routine methods

2023-09-29 21:25 UTC, ekluzek requested changes
Just a couple really small questions and requests...

2023-09-30 22:40 UTC, nmizukami commented on route/build/src/irf_route.f90
> + real(dp)                                 :: q_upstream_mod ! total discharge at top of the reach being processed
Comments corrected.

2023-09-30 22:41 UTC, nmizukami commented on route/build/src/irf_route.f90
> +        RCHFLX_out(iens,segIndex)%ROUTE(idxIRF)%REACH_VOL(1) = 0._dp ! voluem gets 0
typo corrected

2023-09-30 22:45 UTC, nmizukami commented
thank you Erik,   comments should be fixed now.

2023-10-01 00:41 UTC, ekluzek approved these changes

2023-10-01 03:31 UTC, merged